
INNER_JOIN = "INNER JOIN"
FULL_OUTER_JOIN = "FULL OUTER JOIN"
RIGHT_JOIN = "RIGHT JOIN"
LEFT_JOIN = "LEFT JOIN"
JOINS_LIST = [INNER_JOIN, FULL_OUTER_JOIN, RIGHT_JOIN, LEFT_JOIN]
GET_ALL_COLUMNS = ["*"]
ID = "id"
ORDER_BY_ASC = "ASC"
ORDER_BY_DESC = "DESC"
ADD = "ADD"
DROP_COLUMN = "DROP COLUMN"
ALTER_COLUMN = "ALTER COLUMN"
